### ISSUE TITLE
Error when convert: Command substitution

### ISSUE THREAD

**Issue by Owned67** [daniel-sc/bash-shell-to-bat-converter#13]
`node lib/cli.js uasp.sh` (script can be found here: https://github.com/kennethrisa/uasp)

return:
  D:\bash-shell-to-bat-converter\node_modules\bash-parser\src\index.js:52
                throw new Error(err.stack || err.message);
                ^

Error: Parse error on line 34: Unexpected 'OPEN_PAREN'
    at Object.parse [as default] (D:\\bash-shell-to-bat-converter\node_modul
es\bash-parser\src\index.js:52:9)
    at Object.convertBashToWin (D:\\bash-shell-to-bat-converter\lib\convert-
bash.js:69:36)
    at Object.<anonymous> (D:\bash-shell-to-bat-converter\lib\cli.js:9:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

Windows 10
node 10.15.1

**Comment by Owned67** [comment]
I've edited my post because the first line is not really used in this script so error can be ignored but now, i got a new error when trying convert... Thanks for any help

**Comment by daniel-sc** [comment]
Hi  @Owned67,
there are several things that are not supported right now such as functions (#10) and command substition (see e.g. [Stackoverflow](https://stackoverflow.com/questions/2768608/batch-equivalent-of-bash-backticks)). As both are non-trivial, they won't get fixed soon by me. If you want to contribute, I'd be happy to assist :)

**Comment by Owned67** [comment]
Hello, i don't have time sorry...

**Comment by Owned67** [comment]
node lib/cli.js uasp.sh
converting file: uasp.sh ...
F:\bash-shell-to-bat-converter\node_modules\bash-parser\src\index.js:52
                throw new Error(err.stack || err.message);
                ^

Error: Parse error on line 34: Unexpected 'OPEN_PAREN'
    at Object.parse [as default] (F:\bash-shell-to-bat-converter\node_modules\bash-parser\src\index.js:52:9)
    at Object.convertBashToWin (F:\bash-shell-to-bat-converter\lib\convert-bash.js:69:36)
    at Object.<anonymous> (F:\bash-shell-to-bat-converter\lib\cli.js:9:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by flora8984461** [comment]
Got the same issue as well

```
window = { process: { env: { NODE_NEV: 'mock' } } };
^

ReferenceError: window is not defined
```

**Comment by daniel-sc** [comment]
Hi @Owned67 @flora8984461 
The error with the window reference should be fixed with the latest version 2.0.1. Could you please check and confirm if this issue is resolved?

**Comment by Owned67** [comment]
Hello

fresh install:
downloaded  https://github.com/daniel-sc/bash-shell-to-bat-converter/archive/v2.0.1.zip
npm install return:
  updated 1 package and audited 32 packages in 8.948s
  found 0 vulnerabilities

npm run tsc return:
  > bash-converter@0.1.0 tsc F:\rust\bash-shell-to-bat-converter
  > tsc

command: node lib/cli.js uasp.sh return:
`converting file: uasp.sh ...
F:\rust\bash-shell-to-bat-converter\node_modules\bash-parser\src\index.js:52
                throw new Error(err.stack || err.message);
                ^

Error: Parse error on line 34: Unexpected 'OPEN_PAREN'
    at Object.parse [as default] (F:\rust\bash-shell-to-bat-converter\node_modules\bash-parser\src\index.js:52:9)
    at Object.convertBashToWin (F:\rust\bash-shell-to-bat-converter\lib\convert-bash.js:109:36)
    at Object.<anonymous> (F:\rust\bash-shell-to-bat-converter\lib\cli.js:9:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)`

**Comment by flora8984461** [comment]
+1  Just got the same new error

----------------------

> Hello
> 
> fresh install:
> downloaded https://github.com/daniel-sc/bash-shell-to-bat-converter/archive/v2.0.1.zip
> npm install return:
> updated 1 package and audited 32 packages in 8.948s
> found 0 vulnerabilities
> 
> npm run tsc return:
> 
> > bash-converter@0.1.0 tsc F:\rust\bash-shell-to-bat-converter
> > tsc
> 
> command: node lib/cli.js uasp.sh return:
> `converting file: uasp.sh ...
> F:\rust\bash-shell-to-bat-converter\node_modules\bash-parser\src\index.js:52
> throw new Error(err.stack || err.message);
> ^
> 
> Error: Parse error on line 34: Unexpected 'OPEN_PAREN'
> at Object.parse [as default] (F:\rust\bash-shell-to-bat-converter\node_modules\bash-parser\src\index.js:52:9)
> at Object.convertBashToWin (F:\rust\bash-shell-to-bat-converter\lib\convert-bash.js:109:36)
> at Object. (F:\rust\bash-shell-to-bat-converter\lib\cli.js:9:26)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
> at startup (internal/bootstrap/node.js:283:19)`

**Comment by daniel-sc** [comment]
closing this as a duplicate of #51 (I know, this predates the other issue, but here we have comments regarding another issue as well, so the other is cleaner..)
